name: RSS Feed Monitor

on:
  schedule:
    # Run daily at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  monitor-rss-feeds:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Monitor RSS feeds and create issues
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.github/scripts/monitor-rss.ps1 -GitHubToken $env:GITHUB_TOKEN -Repository $env:GITHUB_REPOSITORY
