name: RSS Feed Monitor

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3 AM UTC
  workflow_dispatch:
    # Allow manual trigger

jobs:
  monitor-rss-feeds:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Monitor RSS feeds and create issues
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.github/scripts/monitor-rss.ps1
      
      - name: Commit and push new posts and news
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _posts/ _news/
          if ! git diff --cached --quiet; then
            git commit -m "New posts and news based on RSS feeds"
            git push
          else
            echo "No changes to commit"
          fi
